apiVersion: apps/v1
kind: Deployment
metadata:
  name: objective-devops-test
  labels:
    app: objective-devops-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objective-devops-test-deployment
  template:
    metadata:
      labels:
        app: objective-devops-test-deployment
    spec:
      containers:
      - name: objective-devops-test-deployment
        image: 192.168.1.5:5000/objective-devops-test:dev
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred  